### ISSUE TITLE
Timing difference ?

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-Core#60]
The inject returns 500ms, 1000ms, 1500ms.
When I comment the inject, and uncomment all, the 3 narrates run together as one. No 0.5 delay.
How can it be explained, that this for inject not the case ?

```
    on click:
    - inject profiler path:gStart
    - run chatEngine def:<script> path:loader
```
```
chatEngine:
  type: task
  loader:
  - foreach <player.flag[<npc.flag[enpc]||<npc>>].as_list> {
    - inject profiler path:gStop
    #- narrate 1
    }
```

```
profiler:
  type: task
  gStart:
  - flag server meta.time:<server.current_time_millis>
  gStop:
  - announce "<&e>This action took <server.current_time_millis.sub[<server.flag[meta.time]>]>ms."
```
